title: "Thien's Blog"
description: "A personal blog powered by GitHub Pages and Jekyll."
author:
  name: "Thien"
baseurl: "" # the subpath, e.g. /blog
url: "https://neverdie88.github.io"
markdown: kramdown
plugins: []
theme: null
